import {
  authlogin,
  changePassword,
  createBlog,
  createCarouselImage,
  createCertification,
  createEvent,
  createExpertTeam,
  createFAQ,
  createNewSection,
  createOrganization,
  createSector,
  createSuccessStory,
  createTestimonial,
  createTopbarContent,
  createVideo,
  createVisionMissionItem,
  deleteBlog,
  deleteCarouselImage,
  deleteCertification,
  deleteContactMessage,
  deleteDonation,
  deleteEvent,
  deleteExpertTeam,
  deleteFAQ,
  deleteFooterImage,
  deleteInquiry,
  deleteJobApplication,
  deleteNewSection,
  deleteOrganizationImage,
  deleteSector,
  deleteStory,
  deleteSubmission,
  deleteSuccessStory,
  deleteTestimonial,
  deleteTopbarContent,
  deleteVideo,
  deleteVisionMissionItem,
  deleteVolunteer,
  getActiveFAQs,
  getAllCarouselImages,
  getAllCertifications,
  getAllContent,
  getAllDocuments,
  getAllEvents,
  getAllFAQs,
  getAllOrganizations,
  getAllSectors,
  getAllSubmissions,
  getAllSuccessStories,
  getAllTestimonials,
  getAllTopbarContents,
  getAllVideos,
  getAllVisionMissionItems,
  getBankData,
  getBlogById,
  getCarouselImageById,
  getCertificationById,
  getContactMessageById,
  getContactMessages,
  getDesktopImages,
  getDonationById,
  getDonations,
  getEventById,
  getEventData,
  getFAQById,
  getFooterContent,
  getInquiries,
  getInquiryById,
  getJobApplicationById,
  getJobApplications,
  getMobileImages,
  getOrganizationById,
  getOwner,
  getProfile,
  getSEOData,
  getSectorById,
  getStories,
  getStoriesData,
  getStoryById,
  getSubmissionById,
  getTelephoneData,
  getTestimonialById,
  getTopbarContentById,
  getVisionMissionItemById,
  getVolunteerById,
  getVolunteers,
  getWelcomeSection,
  login,
  logout,
  permanentDeleteSector,
  removeBankLogo,
  restoreSector,
  softDeleteOrganization,
  toggleFAQStatus,
  updateBankData,
  updateBlog,
  updateCarouselImage,
  updateCertification,
  updateDisplayOrder,
  updateDonationStatus,
  updateEvent,
  updateEventData,
  updateExpertTeam,
  updateFAQ,
  updateFooterContent,
  updateNewSection,
  updateOrganization,
  updateOwner,
  updateProfile,
  updateSEOData,
  updateSection,
  updateSector,
  updateSortOrder,
  updateStoriesData,
  updateSuccessStory,
  updateTelephoneData,
  updateTestimonial,
  updateTopbarContent,
  updateVideo,
  updateVisionMissionItem,
  updateWelcomeSection,
} from './admin-backend/controllers/mainController.js';
import { auth } from './admin-backend/middleware/auth.js';

const protectedRoute = (method, path, handler) => ({ method, path, handlers: [auth, handler] });
const openRoute = (method, path, handler) => ({ method, path, handlers: [handler] });

export const routes = [
  openRoute('POST', '/auth/login', login),
  openRoute('POST', '/authlogin', authlogin),
  protectedRoute('POST', '/auth/logout', logout),
  protectedRoute('PUT', '/auth/change-password', changePassword),
  protectedRoute('GET', '/api/profile', getProfile),
  protectedRoute('PUT', '/api/profile', updateProfile),

  protectedRoute('GET', '/organizations', getAllOrganizations),
  protectedRoute('POST', '/api/organizations', createOrganization),
  protectedRoute('GET', '/api/organizations/:id', getOrganizationById),
  protectedRoute('PUT', '/api/organizations/:id', updateOrganization),
  protectedRoute('DELETE', '/api/organizations/:id/images', deleteOrganizationImage),
  protectedRoute('POST', '/api/delete/:id', softDeleteOrganization),

  protectedRoute('GET', '/api/documents', getAllDocuments),
  protectedRoute('GET', '/api/blogs/:id', getBlogById),
  protectedRoute('POST', '/api/blogs', createBlog),
  protectedRoute('PUT', '/api/blogs/:id', updateBlog),
  protectedRoute('DELETE', '/api/documents/:id', deleteBlog),

  protectedRoute('GET', '/api/success-stories', getAllSuccessStories),
  protectedRoute('POST', '/api/success-stories', createSuccessStory),
  protectedRoute('PUT', '/api/success-stories/:id', updateSuccessStory),
  protectedRoute('DELETE', '/api/success-stories/:id', deleteSuccessStory),

  protectedRoute('GET', '/api/videos', getAllVideos),
  protectedRoute('POST', '/api/videos', createVideo),
  protectedRoute('PUT', '/api/videos/:id', updateVideo),
  protectedRoute('DELETE', '/api/videos/:id', deleteVideo),

  protectedRoute('GET', '/admin/inquiries', getInquiries),
  protectedRoute('GET', '/admin/inquiries/:id', getInquiryById),
  protectedRoute('GET', '/admin/owner', getOwner),
  protectedRoute('PUT', '/admin/owner', updateOwner),
  protectedRoute('DELETE', '/admin/inquiries/:id', deleteInquiry),

  protectedRoute('GET', '/admin/donations', getDonations),
  protectedRoute('GET', '/admin/donations/:id', getDonationById),
  protectedRoute('DELETE', '/admin/donations/:id', deleteDonation),
  protectedRoute('PATCH', '/admin/donations/:id/status', updateDonationStatus),

  protectedRoute('GET', '/admin/stories', getStories),
  protectedRoute('GET', '/admin/stories/:id', getStoryById),
  protectedRoute('DELETE', '/admin/stories/:id', deleteStory),

  protectedRoute('GET', '/admin/job-applications', getJobApplications),
  protectedRoute('GET', '/admin/job-applications/:id', getJobApplicationById),
  protectedRoute('DELETE', '/admin/job-applications/:id', deleteJobApplication),

  protectedRoute('GET', '/admin/volunteers', getVolunteers),
  protectedRoute('GET', '/admin/volunteers/:id', getVolunteerById),
  protectedRoute('DELETE', '/admin/volunteers/:id', deleteVolunteer),

  protectedRoute('GET', '/admin/contact-messages', getContactMessages),
  protectedRoute('GET', '/admin/contact-messages/:id', getContactMessageById),
  protectedRoute('DELETE', '/admin/contact-messages/:id', deleteContactMessage),

  protectedRoute('GET', '/api/topbar', getAllTopbarContents),
  protectedRoute('GET', '/api/topbar/:id', getTopbarContentById),
  protectedRoute('POST', '/api/topbar', createTopbarContent),
  protectedRoute('PUT', '/api/topbar/:id', updateTopbarContent),
  protectedRoute('DELETE', '/api/topbar/:id', deleteTopbarContent),

  protectedRoute('GET', '/certifications', getAllCertifications),
  protectedRoute('GET', '/certifications/:id', getCertificationById),
  protectedRoute('POST', '/certifications', createCertification),
  protectedRoute('PUT', '/certifications/:id', updateCertification),
  protectedRoute('DELETE', '/certifications/:id', deleteCertification),

  protectedRoute('GET', '/testimonials', getAllTestimonials),
  protectedRoute('GET', '/testimonials/:id', getTestimonialById),
  protectedRoute('POST', '/testimonials', createTestimonial),
  protectedRoute('PUT', '/testimonials/:id', updateTestimonial),
  protectedRoute('DELETE', '/testimonials/:id', deleteTestimonial),

  protectedRoute('GET', '/events', getAllEvents),
  protectedRoute('GET', '/events/:id', getEventById),
  protectedRoute('POST', '/events', createEvent),
  protectedRoute('PUT', '/events/:id', updateEvent),
  protectedRoute('DELETE', '/events/:id', deleteEvent),

  protectedRoute('GET', '/sectors/admin', getAllSectors),
  protectedRoute('GET', '/sectors/admin/:id', getSectorById),
  protectedRoute('POST', '/sectors/admin', createSector),
  protectedRoute('PUT', '/sectors/admin/:id', updateSector),
  protectedRoute('DELETE', '/sectors/admin/:id', deleteSector),
  protectedRoute('PATCH', '/sectors/admin/restore/:id', restoreSector),
  protectedRoute('DELETE', '/sectors/admin/permanent/:id', permanentDeleteSector),

  protectedRoute('GET', '/api/carousel/desktop', getDesktopImages),
  protectedRoute('GET', '/api/carousel/mobile', getMobileImages),
  protectedRoute('GET', '/api/carousel', getAllCarouselImages),
  protectedRoute('GET', '/api/carousel/:id', getCarouselImageById),
  protectedRoute('POST', '/api/carousel', createCarouselImage),
  protectedRoute('PUT', '/api/carousel/:id', updateCarouselImage),
  protectedRoute('DELETE', '/api/carousel/:id', deleteCarouselImage),

  protectedRoute('GET', '/api/welcome', getWelcomeSection),
  protectedRoute('PUT', '/api/welcome', updateWelcomeSection),

  protectedRoute('GET', '/api/vision-mission', getAllVisionMissionItems),
  protectedRoute('GET', '/api/vision-mission/:id', getVisionMissionItemById),
  protectedRoute('POST', '/api/vision-mission', createVisionMissionItem),
  protectedRoute('PUT', '/api/vision-mission/:id', updateVisionMissionItem),
  protectedRoute('DELETE', '/api/vision-mission/:id', deleteVisionMissionItem),
  protectedRoute('PATCH', '/api/vision-mission/sort', updateSortOrder),

  protectedRoute('GET', '/api/stories', getStoriesData),
  protectedRoute('PUT', '/api/stories', updateStoriesData),
  protectedRoute('GET', '/api/events', getEventData),
  protectedRoute('PUT', '/api/events', updateEventData),
  protectedRoute('GET', '/api/telephone', getTelephoneData),
  protectedRoute('PUT', '/api/telephone', updateTelephoneData),

  protectedRoute('GET', '/api/content', getAllContent),
  protectedRoute('PUT', '/api/content/section/:section', updateSection),
  protectedRoute('POST', '/api/content/expert-team', createExpertTeam),
  protectedRoute('PUT', '/api/content/expert-team/:id', updateExpertTeam),
  protectedRoute('DELETE', '/api/content/expert-team/:id', deleteExpertTeam),
  protectedRoute('POST', '/api/content/new-section', createNewSection),
  protectedRoute('PUT', '/api/content/new-section/:id', updateNewSection),
  protectedRoute('DELETE', '/api/content/new-section/:id', deleteNewSection),

  protectedRoute('GET', '/api/seo', getSEOData),
  protectedRoute('PUT', '/api/seo', updateSEOData),
  protectedRoute('GET', '/api/footer', getFooterContent),
  protectedRoute('PUT', '/api/footer', updateFooterContent),
  protectedRoute('DELETE', '/api/footer/image/:imageType', deleteFooterImage),

  protectedRoute('GET', '/api/faqs/public', getActiveFAQs),
  protectedRoute('GET', '/api/faqs', getAllFAQs),
  protectedRoute('GET', '/api/faqs/:id', getFAQById),
  protectedRoute('POST', '/api/faqs', createFAQ),
  protectedRoute('PUT', '/api/faqs/display-order/update', updateDisplayOrder),
  protectedRoute('PUT', '/api/faqs/:id/toggle', toggleFAQStatus),
  protectedRoute('PUT', '/api/faqs/:id', updateFAQ),
  protectedRoute('DELETE', '/api/faqs/:id', deleteFAQ),

  protectedRoute('GET', '/api/bank', getBankData),
  protectedRoute('PUT', '/api/bank', updateBankData),
  protectedRoute('DELETE', '/api/bank/logo', removeBankLogo),

  protectedRoute('GET', '/api/admin/submissions', getAllSubmissions),
  protectedRoute('GET', '/api/admin/submissions/:id', getSubmissionById),
  protectedRoute('DELETE', '/api/admin/submissions/:id', deleteSubmission),
];
