import {
  AddVolunteer,
  ApplyForJob,
  ContributeStory,
  DetailForAll,
  Donation,
  createContactInquiry,
  getActiveFAQs,
  getAllBlogs,
  getAllCarouselImages,
  getAllCertifications,
  getAllContent,
  getAllEvents,
  getAllIcons,
  getAllSectors,
  getAllTestimonials,
  getAllTopbarContents,
  getAllVideos,
  getAllVisionMissionItems,
  getAllorganization,
  getBankData,
  getCBN,
  getEventData,
  getFooterContent,
  getSEOData,
  getSimilarItems,
  getSocials,
  getSpecificBlog,
  getSpecificItem,
  getStoriesData,
  getStoryBySlug,
  getTelephoneData,
  getWelcomeSection,
  getsuccessstories,
  itemByCategory,
  saveContacts,
  submitOrganizationForm,
} from './public-backend/controller/index.js';

const route = (method, path, handler) => ({ method, path, handlers: [handler] });

export const routes = [
  route('GET', '/items', getAllorganization),
  route('GET', '/item/:slug', getSpecificItem),
  route('GET', '/icons/:id', getAllIcons),
  route('GET', '/socials/:item_id', getSocials),
  route('GET', '/Blog/:slug', getSpecificBlog),
  route('GET', '/getAllBlogs', getAllBlogs),
  route('GET', '/getSimilarItem', getSimilarItems),
  route('POST', '/api/contact', saveContacts),
  route('POST', '/api/volunteer', AddVolunteer),
  route('POST', '/api/job-application', ApplyForJob),
  route('POST', '/api/contribute-story', ContributeStory),
  route('POST', '/api/donations', Donation),
  route('GET', '/itemByCategory/:name', itemByCategory),
  route('GET', '/getsuccessstories', getsuccessstories),
  route('GET', '/getAllVedios', getAllVideos),
  route('POST', '/contact-inquiry', createContactInquiry),
  route('GET', '/api/topbar', getAllTopbarContents),
  route('GET', '/certifications', getAllCertifications),
  route('GET', '/testimonials', getAllTestimonials),
  route('GET', '/events', getAllEvents),
  route('GET', '/getAllSectors', getAllSectors),
  route('GET', '/CBN/:slug', getCBN),
  route('GET', '/getCrouselimages', getAllCarouselImages),
  route('GET', '/api/welcome', getWelcomeSection),
  route('GET', '/api/vision-mission', getAllVisionMissionItems),
  route('GET', '/api/stories', getStoriesData),
  route('GET', '/api/events', getEventData),
  route('GET', '/api/telephone', getTelephoneData),
  route('GET', '/api/footer', getFooterContent),
  route('GET', '/api/getabout', getAllContent),
  route('GET', '/api/seo', getSEOData),
  route('GET', '/api/faqs', getActiveFAQs),
  route('GET', '/api/bank', getBankData),
  route('GET', '/detail/:slug', DetailForAll),
  route('GET', '/success-story/:slug', getStoryBySlug),
  route('POST', '/api/organization/submit', submitOrganizationForm),
];
